package com.book.bookservice.model;

public enum Categorie {
    FICTION,
    NON_FICTION,
    JEUNESSE,
    BANDES_DESSINEES_MANGAS,
    REFERENCE,
    SCIENCES_TECHNOLOGIES,
    ARTS_LOISIRS,
    SCIENCES_SOCIALES_HUMAINES,
    LITTERATURE_CRITIQUE_LITTERAIRE,
    VOYAGE_GEOGRAPHIE
}
