spring:
  cloud:
    config:
      import-check:
        enabled: false
      enabled: false
    gateway:
      routes:
        - id: r1
          uri: http://localhost:8081/
          predicates:
            - Path=/book/**
    discovery:
      enabled: false
server:
  port: 8888